### ISSUE TITLE
Would you consider commit 9d75de8 stable enough for version pinning?

### ISSUE THREAD

**Issue by atc0005** [orijtech/httperroryzer#3]
Hi,

I saw your post on Twitter about this project and plan to bundle it within a CI container image that I use. Would you consider 9d75de8cdf66f34670c84aeef3c2b698b001fd44 stable enough for use?

Thanks.

**Comment by odeke-em** [comment]
Hello @atc0005, thank you for the question and welcome to Orijtech projects!
I've cut a release [httperroryzer@v0.0.1](https://github.com/orijtech/httperroryzer/releases/tag/v0.0.1) and you can use that.

**Comment by atc0005** [comment]
> Hello @atc0005, thank you for the question and welcome to Orijtech projects!
> I've cut a release [httperroryzer@v0.0.1](https://github.com/orijtech/httperroryzer/releases/tag/v0.0.1) and you can use that.

Thanks!
